from tkinter import *
from tkinter import messagebox
import firebase_newpost_handler
from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


def new_post_wins():
    # SETTING UP WINDOW AND SETTING
    top = Toplevel()
    top.resizable(width=False, height=False)

    # COMMANDS

    # SENDING POST DATA
    def send_post_data():
        # GETTING MESSAGE
        msg = post_entry.get()
        print(msg)

        # SENDING POST TO FIREBASE
        send_post_result = firebase_newpost_handler.send_post(msg)

        # CHECK IF POST SENT
        if send_post_result == 1:
            messagebox.showinfo(title="Info Message", message="Post successfully sent")
        else:
            messagebox.showerror(title="Error 404", message="Message not sent")

    # ==================================================================================================

    # UI
    # The UI section of the file was generated by the Tkinter Designer by Parth Jadhav
    # https://github.com/ParthJadhav/Tkinter-Designer

    OUTPUT_PATH = Path(__file__).parent
    ASSETS_PATH = OUTPUT_PATH / Path(r"assets\new_post_page")

    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    top.geometry("418x232")
    top.configure(bg="#FFFFFF")

    # WINDOW STYLE
    canvas = Canvas(
        top,
        bg="#FFFFFF",
        height=232,
        width=418,
        bd=0,
        highlightthickness=0,
        relief="ridge"
    )

    # TITLE
    canvas.place(x=0, y=0)
    title_image = PhotoImage(
        file=relative_to_assets("image_1.png"))
    title = canvas.create_image(
        209.0,
        38.0,
        image=title_image
    )

    # =========NEW=POST=ENTRY=========

    # NEW POST ENTRY IMAGE
    post_entry_image = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    post_entry_bg = canvas.create_image(
        209.5,
        119.0,
        image=post_entry_image
    )

    # NEW POST ENTRY
    post_entry = Entry(
        top,
        bd=0,
        bg="#D9D9D9",
        fg="#000716",
        highlightthickness=0
    )
    post_entry.place(
        x=26.0,
        y=99.0,
        width=367.0,
        height=38.0
    )

    # =========NEW=POST=BUTTON=========

    # BUTTON IMAGE
    post_btn_image = PhotoImage(
        file=relative_to_assets("button_1.png"))

    # POST BUTTON
    post_btn2 = Button(
        top,
        image=post_btn_image,
        borderwidth=0,
        highlightthickness=0,
        command=send_post_data,
        relief="flat"
    )
    post_btn2.place(
        x=10.0,
        y=162.0,
        width=94.0,
        height=41.0
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        369.0,
        37.0,
        image=image_image_2
    )

    top.mainloop()

